aladin_path: Aladin.jar
cwd: /home/singulani/projects/hipsimage_gen/proc01
max_memory: 5

hipsgen:
  creator_did: CDS/P/DES/DR2
  maxthread: 20
  hips_creator: LIneA
  obs_title: 'LSST DP0'
  incremental: true
  mode: mean

colors:
  blue:
    input_dir: ./input_g
    output_dir: ./output_g
    pixelcut: "-1.2 400 asinh"
    cache: ./tmp_g
  red:
    input_dir: ./input_r
    output_dir: ./output_r
    pixelcut: "-1.2 400 asinh"
    cache: ./tmp_r
  green:
    input_dir: ./input_i
    output_dir: ./output_i
    pixelcut: "-1 400 asinh"
    cache: ./tmp_i
  rgb:
    luptonM: "0.02/0.02/0.02"
    luptonS: "0.005/0.005/0.007"
    luptonQ: "30/30/30"

